export const DESCARGAR_GIPHY = 'DESCARGAR_GIPHY';
export const DESCARGAR_GIPHY_EXITO = 'DESCARGAR_GIPHY_EXITO';
export const DESCARGAR_GIPHY_ERROR = 'DESCARGAR_GIPHY_ERROR';

export const CAMBIAR_PAGE = 'CAMBIAR_PAGE';

export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';