export const DESCARGAR_GIPHY = 'DESCARGAR_GIPHY';
export const DESCARGAR_GIPHY_EXITO = 'DESCARGAR_GIPHY_EXITO';
export const DESCARGAR_GIPHY_ERROR = 'DESCARGAR_GIPHY_ERROR';

export const CAMBIAR_PAGE = 'CAMBIAR_PAGE';

export const BUSCAR_GIPHY = 'BUSCAR_GIPHY';
export const BUSCAR_GIPHY_EXITO = 'BUSCAR_GIPHY_EXITO';
export const BUSCAR_GIPHY_ERROR = 'BUSCAR_GIPHY_ERROR';